# Generated by Django 6.0.3 on 2026-04-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='plan',
            field=models.CharField(choices=[('3M', '3 Months'), ('6M', '6 Months'), ('1Y', '1 Year')], max_length=10),
        ),
    ]
