# Generated by Django 6.0.3 on 2026-04-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='coin',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('BNB', 'BNB'), ('SOL', 'Solana')], default='BTC', max_length=10),
        ),
    ]
